### PR TITLE
feat: allow symfony6, add missing doctrine/orm in composer.json

### PR DESCRIPTION
**Pull request by art-cg**
Hi, 

this is not yet tested. Due to missing test-config in this bundle.
I am working on that in another [PR](https://github.com/metaclass-nl/filter-bundle/pull/4).

I added  "doctrine/orm" as dependency. But i am not sure about the minimum version.
Would be great if you can have a look at this PR.

Greetz

### CODE REVIEW

**Comment by metaclass-nl** [comment]
Thanks a lot, sounds very nice, i'll take a quick look friday, but it may take more time before i can really look into it. I am currently working on something else and need to finisch that before i can really spend time on this.

**Comment by metaclass-nl** [comment]
Thanks a lot, sounds very nice, i'll take a quick look friday, but it may take more time before i can really look into it. I am currently working on something else and need to finisch that before i can really spend time on this.

**Comment by metaclass-nl** [comment]
Thanks!

I did not add a doctrine/orm dependency because the composer.json of api-platform already does. I do not want maintain all version numbers of all inderect dependencies. If api platform is maintained correctly according to semantic versioning rules there should not be any breaking of backward compatibility unless a major version number is released. I thought with the config 
```json composer
"api-platform/core": "^2.5"
```
composer will not install any new major versions of api platform so erverything should keep working. But maybe i am wrong and should there be a config for every dependency whose methods are called directly by the code in the bundle. Then it should be
```json composer
"doctrine/orm": "^2.8",
```
Because that is in the config of the app within which i tested the bundle.

I have seen the [api-platform/core issue about Symfony 6](https://github.com/api-platform/core/issues/4543) but i figured it would be part of the next major version, but now i see 
v2.6.7 requires 
```json composer
"symfony/http-kernel": "^4.4 || ^5.1 || ^6.0",
```
But if i should include a config for every dependency whose methods are called directly by the code in the bundle, i can not merge this until i tested it with Symfony 6.0. That will take some time.

**Comment by art-cg** [comment]
Thanks for taking a look inside this PR.
`"api-platform/core"` does not require  `"doctrine/orm"`: see https://packagist.org/packages/api-platform/core
But beside of that, it is considered best practice to require all libs that are required for the basic code to work. (optional things in "suggests"). It is easier to test and work on the bundle.
I changed it to "doctrine/orm": "^2.8"
It is your bundle, so you habe the right to decide.

Maybe my other (unfinished) PR helps with testing.

**Pull request merged**
